### ISSUE TITLE
Passwords - show/hide slight glitch with focus display

### ISSUE THREAD

**Issue by elisa-est** [Energy-Saving-Trust/Design-System#81]
**This is related to this issue: https://github.com/Energy-Saving-Trust/Design-System/issues/64**

![image](https://github.com/user-attachments/assets/02e73183-233c-4d89-881f-f9c10b9db116)

We need to figure out how to fix the show/hide on the passwords. When you click it looks odd to only see part of the input box in the outline.

We need to figure out a solution for how to display this. It seems to be a common issue across our components (also with the search input I know we ran into this). 

**What are the possible solutions to this?**
Once we have them listed we can weigh the pros and cons and select the best option.

**Comment by bobbyCHD** [comment]
Fixed in my latest commit
